### ISSUE TITLE
How to get this working?

### ISSUE THREAD

**Issue by BalajiX5** [WeaveAche/hanime-auto-coins-collector#13]
<img width="826" alt="Screenshot 2023-02-13 165354" src="https://user-images.githubusercontent.com/125268449/218445194-4dca8e94-fdd6-4245-8f42-9585cb8d0809.png">
<img width="847" alt="Screenshot 2023-02-13 170227" src="https://user-images.githubusercontent.com/125268449/218447192-e80906da-b8f6-409e-8a05-655a516c937e.png">

1. I have downloaded the folder.
2. I have installed all the pip install -requirements.txt
3. I have opened the .env filed and entered hanime username and password.
4.  placed the  hanime ps file in startup. 
5.  how to run this file pls. help

**Please Help, I am not a programmer and would be much grateful if there is a step by step instructions. Thank you.

**Comment by Praveensenpai** [comment]
run : python getcoins.py

**Comment by WeaveAche** [comment]
Don't use the hanime.ps script (it was just an example script someone created), I've removed it in the recent commit because it was a bit confusing. As @Praveensenpai has mentioned, you need to run python getcoins.py to get the coins. It'll only work for once and you'll be able to get coins again only after 3 hours.

**Comment by Praveensenpai** [comment]
> Don't use the hanime.ps script (it was just an example script someone created), I've removed it in the recent commit because it was a bit confusing. As @Praveensenpai has mentioned, you need to run python getcoins.py to get the coins. It'll only work for once and you'll be able to get coins again only after 3 hours.

Bro it's out of topic...
I run the script on the railway .... so it'll automatically collect coins so far it collected 40k coins...
the railway give 500 hours so you need 2 accounts it's free u just need 2 github accounts to fully use the script in a month

so what I was saying is add a README where u instruct them to how to run it in a railway or any cloud.... so they can automatically collect coins

**Comment by BalajiX5** [comment]
Thanks everyone. Sorry for the late reply. I will try them.
