### ISSUE TITLE
Logs are glitched

### ISSUE THREAD

**Issue by sneazy-ibo** [WeaveAche/hanime-auto-coins-collector#5]
The logs are often glitched f.e. random numbers between the text and lately I am also getting a Error on the logs but it's still working. It also says that the coins already got claimed although they shouldn't be claimed before.

![Screenshot_20220427-195909_Microsoft Remote Desktop.jpg](https://user-images.githubusercontent.com/41344259/165590716-9dfc3a4e-ab24-467b-ad44-b529686efb2a.jpg)

![Screenshot_20220427-195921_HTV 371.jpg](https://user-images.githubusercontent.com/41344259/165590749-a24a309f-92de-41b1-984d-e647e4d61c95.jpg)

**Comment by WeaveAche** [comment]
That is weird, I use the script myself and I've never had something like this happen to me. I doubt it's an issue on the script itself, it'd help if you could provide your script and batch file.

**Comment by sneazy-ibo** [comment]
> That is weird, I use the script myself and I've never had something like this happen to me. I doubt it's an issue on the script itself, it'd help if you could provide your script and batch file.

That is my current batch script, I added a start where I can customize the first run bc I sometimes claim it accidentally by testing stuff. I only edited the timezone part in the getcoins.py

![Screenshot_20220428-104950_Microsoft Remote Desktop.jpg](https://user-images.githubusercontent.com/41344259/165715583-2303b323-edb6-450d-b09d-6a918a9acb36.jpg)

**Comment by WeaveAche** [comment]
I'm not sure why it's happening. But since it's not an issue in the script itself, I'm closing the issue for now.
