### ISSUE TITLE
Total Coins

### ISSUE THREAD

**Issue by trestlesky** [WeaveAche/hanime-auto-coins-collector#6]
Love the script, thank you for your hard work. This is purely a QOL suggestion...was wondering if in the output you could add a new total coin amount? I personally would use it to trigger an alert to tell me when I had the 4100 needed for premium. Something like:

[*] Logged in as john_doe
[*] Coins count: 1000
[*] Last clicked on Mon Jan 1 00:00:00 2022 UTC
You received 120 coins. 
New total coins: 1120

I could then set up an alert to trigger immediately after that run, instead of waiting the full three hours to get the coin total the next run. Absolutely no worries if you can't find the time. Thanks again!

**Comment by Fredwuz** [comment]
you can just add 
```python
info = login(s, hanime_email, hanime_password)
print(f"[*] New Coins count: {info['coins']}")
 ```
 underneath here
https://github.com/WeaveAche/hanime-auto-coins-collector/blob/fb570ca25e346b5c1ed465bf88ef8533ffcaeea0/getcoins.py#L91-L93

like so 

```python
print(f"[+] You received {json.loads(response.text)['rewarded_amount']} coins.")
info = login(s, hanime_email, hanime_password)
print(f"[*] New Coins count: {info['coins']}")
```
and then the output will look like this 

```
[*] Logged in as Username
[*] Coins count: 10000
[*] Last clicked on Thu Aug 10 12:00:00 2022 UTC
[+] You received 73 coins.
[*] New Coins count: 10073
```

**Comment by trestlesky** [comment]
Awesome, this is great. Thanks!

**Comment by Praveensenpai** [comment]
@trestlesky bro u should close the issues if it's solved.
